[mitm]
skip_validating_cert = true
hostname = app.uanalyze.com.tw, api.uanalyze.com.tw

[rewrite_local]
^https?:\/\/(app|api)\.uanalyze\.com\.tw url script-response-body https://raw.githubusercontent.com/loveks520/QuXscript/refs/heads/main/K_88s.js
#^https?:\/\/api\.iaphub\.com\/v1\/app\/ url script-response-body https://raw.githubusercontent.com/loveks520/QuXscript/refs/heads/main/K_88s.js
