[mitm]
hostname = app.uanalyze.com.tw, api.uanalyze.com.tw, api.iaphub.com

[rewrite_local]
^https?:\/\/(app|api)\.uanalyze\.com\.tw url script-response-body uanalyze_debug.js
^https?:\/\/api\.iaphub\.com url script-response-body uanalyze_debug.js
#^https?:\/\/api\.iaphub\.com\/v1\/app\/ url script-response-body https://raw.githubusercontent.com/loveks520/QuXscript/refs/heads/main/K_88s.js
